### ISSUE TITLE
Data Kelurahan

### ISSUE THREAD

**Issue by ghk** [ghk/kawaldesa#3]
Kelurahan dan Desa diperlakukan berbeda pada UU & Pepres Desa. Data wilayah dari KPU/kawalpemilu.org, yang sekarang digunakan kawaldesa, tidak menyediakan informasi ini.

**Comment by opikcumin** [comment]
Perkenalkan saya Opick, koord data dan informasi FITRA.
Saya tertarik dengan website kawaldesa.org dan saya bisa update data-data baru. Bagaimana caranya? Baik info desa ataupun data anggarannya (simulasi).

**Comment by ghk** [comment]
Halo Mas Opik dan teman-teman yang lain yang ingin membantu,

Maaf kemarin tidak keurus, sekarang ada momen lagi sih, baru bertemu beberapa lembaga dan relawan. Jadi kalau masih tertarik membantu mungkin bisa email saya contact/email di ghk@gozalikumara.com

Dan data desa dan kelurahan ini belum dapet sih kita, jadi kalau bisa membantu akan sangat diapresiasi.

Btw, ada thread kawaldesa juga di https://code4nation.org/t/kawaldesa-dana-desa-tersangkut-di-kabupaten/221

**Comment by opikcumin** [comment]
Hallo juga mas Gozali,

Kami dari Seknas FITRA sudah melakukan simulasi dana desa tersebut. Secara
sumber keuangan desa ada 7 sumber pendapatan desa.
1. Pendapatan Asli Desa, terdiri atas hasil usaha, hasil aset, swadaya dan
   partisipasi, gotong royong, dan lain-lain pendapatan asli Desa;
2. Alokasi APBN; (dana desa)
3. Bagian dari hasil Pajak Daerah dan Retribusi Daerah Kab./Kota;
4. Alokasi Dana Desa yang merupakan bagian dari dana perimbangan yang
   diterima Kab./Kota;
5. Bantuan keuangan dari APBD Provinsi dan APBD Kab./Kota;
6. Hibah dan sumbangan yang tidak mengikat dari pihak ketiga; dan
7. Lain-lain pendapatan Desa yang sah.

Nah, nomer 2, 3 dan 4 adalah yang bisa disimulasikan (selama data
pendukungnya ada).

Saya sangat senang dan apresiasi dengan kawaldesa. Saat ini kami ada data
untuk membuat simulasi 2,3 dan 4 tadi. Seperti data dana desa (DD) dari
APBN-Perubahan 2015, kemudian APBD 2015 dan juga data statistik terkait
jumlah desa, kelurahan, kecamatan dan luas wilayah dari permendagri seperti
yang sudah disebut nazhir (
http://www.kemendagri.go.id/basis-data/2015/03/02/permendagri-ri-no39-tahun-2015-tentang-kode-dan-data-wilayah-administrasi-pemerintahan
)

Jika ada pertemuan (kopdar) saya ingin bisa gabung untuk sharing knowledge
dan data.

Terima Kasih atas respon dari Mas Gozali.

Opick

Pada 15 Juni 2015 22.30, Gozali Kumara notifications@github.com menulis:

> Halo Mas Opik dan teman-teman yang lain yang ingin membantu,
> 
> Maaf kemarin tidak keurus, sekarang ada momen lagi sih, baru bertemu
> beberapa lembaga dan relawan. Jadi kalau masih tertarik membantu mungkin
> bisa email saya contact/email di ghk@gozalikumara.com
> 
> Dan data desa dan kelurahan ini belum dapet sih kita, jadi kalau bisa
> membantu akan sangat diapresiasi.
> 
> Btw, ada thread kawaldesa juga di
> https://code4nation.org/t/kawaldesa-dana-desa-tersangkut-di-kabupaten/221
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghk/kawaldesa/issues/3#issuecomment-112110470.

## 

*Achmad TaufikKoord. Data dan InformasiKnowledge Management
Division-------------------------------------------------------------------------Seknas
FITRASekretariat Nasional Forum Indonesia untuk Transparansi
AnggaranMampang Prapatan IV, Jl. K No. 37 Rt. 006/04 Kel. Mampang Prapatan
- Jakarta Selatan 12790Tel/Fax: 021-7947608  Ext.
  113http://www.seknasfitra.org http://www.seknasfitra.orgHP. 0813 19 7997
  42Email. opik@seknasfitra.org http://seknasfitra.org*

**Comment by ghk** [comment]
Mas mau email doong, mau saya invite ke trello https://trello.com/b/9oj3q4WV/kawaldesa-org

**Comment by opikcumin** [comment]
opikcumin@gmail.com
Pada 17 Jun 2015 04:39, "Gozali Kumara" notifications@github.com menulis:
